version: '2'
services:
  fast-data-dev:
    build: ./fast-data-dev-rethinkdb-client
    image: landoop/fast-data-dev-rethinkdb-client
    depends_on:
      - rethinkdb
    environment:
      - ADV_HOST=fast-data-dev
      - FORWARDLOGS=0
      - RUNTESTS=0
      - CONNECTORS=rethink
    # ports:
    #   - 3030:3030
  rethinkdb:
    image: rethinkdb
