version: '2'
services:
  fast-data-dev:
    build:
      context: ./fast-data-dev-mqtt-client
    image: landoop/fast-data-dev-mqtt-client
    depends_on:
      - activemq
    volumes:
      - ./schema.avro:/schema.avro
    environment:
      - ADV_HOST=fast-data-dev
      - FORWARDLOGS=0
      - RUNTESTS=0
      - CONNECTORS=mqtt
    ports:
      - 3030:3030

  activemq:
    build:
      context: ./activemq
      args:
        ACTIVEMQ_VERSION: 5.14.5
        ACTIVEMQ_ADMIN: "landoop: landoop, admin"
        ACTIVEMQ_USER: "test: test, user"
    ports:
      - 8161:8161
      - 61616:61616
    image: landoop/activemq
