version: '2'
services:
  fast-data-dev:
    image: landoop/fast-data-dev-ui:latest
    depends_on:
      - elasticsearch
    environment:
      - ADV_HOST=fast-data-dev
      - FORWARDLOGS=0
      - RUNTESTS=0
    ports:
      - 3030:3030
  elasticsearch:
    image: elasticsearch:2.4
    command: --cluster.name landoop
    # for elasticsearch 5
    # command: -E "cluster.name=landoop"
