version: '2'
services:
  fast-data-dev:
    build:
      context: ./fast-data-dev-activemq
      args:
        ACTIVEMQ_VERSION: 5.14.5
    image: landoop/fast-data-dev-activemq
    depends_on:
      - activemq
    environment:
      - ADV_HOST=fast-data-dev
      - FORWARDLOGS=0
      - RUNTESTS=0
      - CONNECTORS=jms
    # ports:
    #   - 3030:3030
  activemq:
    build:
      context: ./activemq
      args:
        ACTIVEMQ_VERSION: 5.14.5
        ACTIVEMQ_ADMIN: "landoop: landoop, admin"
        ACTIVEMQ_USER: "test: test, user"
    image: landoop/activemq
