version: '2'
services:
  fast-data-dev:
    image: landoop/fast-data-dev:latest
    depends_on:
      - cassandra
    environment:
      - ADV_HOST=fast-data-dev
      - FORWARDLOGS=0
      - RUNTESTS=0
      - CONNECTORS=cassandra
    ports:
      - 3030:3030
  cassandra:
    build: ./cassandra
    image: landoop/cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
