version: '2'
services:
  fast-data-dev:
    image: landoop/fast-data-dev
    depends_on:
      - redis
    environment:
      - ADV_HOST=fast-data-dev
      - RUNTESTS=0
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
