version: '2'
services:
  fast-data-dev:
    image: landoop/fast-data-dev:latest
    depends_on:
      - kudu
    environment:
      - ADV_HOST=fast-data-dev
      - FORWARDLOGS=0
      - RUNTESTS=0
      - CONNECTORS=kudu
    # ports:
    #   - 3030:3030
  kudu:
    build: ./kudu
    image: landoop/kudu

