version: '2'
services:
  fast-data-dev:
    build: ./fast-data-dev-hbase
    image: landoop/fast-data-dev-hbase
    environment:
      - ADV_HOST=fast-data-dev
      - FORWARDLOGS=0
      - RUNTESTS=0
      - CONNECTORS=hbase
    # ports:
    #   - 3030:3030
