version: '2'
services:
  fast-data-dev:
    build: ./fast-data-dev-hbase
    image: landoop/fast-data-dev-hbase
    environment:
      - ADV_HOST=fast-data-dev
      - PREFER_HBASE=true
      - FORWARDLOGS=0
      - RUNTESTS=0
    ports:
      - 3030:3030
