version: '2'
services:
  fast-data-dev:
    image: landoop/fast-data-dev:latest
    depends_on:
      - pulsar
    environment:
      - ADV_HOST=fast-data-dev
      - FORWARDLOGS=0
      - RUNTESTS=0
      - CONNECTORS=pulsar
    # ports:
    #   - 3030:3030
  pulsar:
    image: streamlio/pulsar
    command: bin/pulsar standalone --advertised-address pulsar
